# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 236b36bc3c6c51ad5249727b81659ce8346e7dde2335e6292fe36b81ddcdd0b231d66c7347db11fbd2b893377da6c806babb9f8e3fd027be5f090ff81ca1f0dd

test:
  secret_key_base: c6b8358e7be7fe678df4ecd016094de181a581a5aa68f3c054495b2adcec272eae786d352034a48085c964e1a03f48e765a07d6b60bd3d185e43aacf261f140e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
